# Deploys the specified docker image as a Container App.

# https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows

name: Deploy Container App

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image-tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Set env
        id: env
        uses: actions/github-script@v6
        with:
          script: |
            switch('${{ inputs.environment }}') {
              case 'staging':
                return "stg"
              case 'production':
                return "prd"
              default:
                return "dev"
            }
          result-encoding: string

      - uses: actions/checkout@v3

      # simplify manage bicep parameter management
      - name: Set params
        id: params
        uses: actions/github-script@v6
        with:
          script: |
            // const apiSpec = require('./gen/proto/openapi/docs.swagger.json')

            let p = 'env=${{ steps.env.outputs.result }}';
            p += ' appName=${{ github.event.repository.name }}';
            p += ' imageTag=${{ inputs.image-tag }}';
            p += ' ghcrUser=${{ secrets.GHCR_USER }}';
            p += ' ghcrPat=${{ secrets.GHCR_PAT }}';
            // p += ' apiSpec=' + apiSpec;
            return p
          result-encoding: string

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Container App
        uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.event.repository.name }}
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: app-ticc-${{ steps.env.outputs.result }}-ae-rg
          template: ./.github/workflows/main.bicep
          # template: https://raw.githubusercontent.com/ticctech/github-actions/main/bicep/containerapp.bicep
          additionalArguments: "--template-spec ts:4e6ec3dd-7f2a-4679-86fc-1cc8297b48cd/app-ticc-stg-ae-rg/ts-containerapp:1.0"
          parameters: ./.github/workflows/params.json ${{ steps.params.outputs.result }}
          failOnStdErr: false
