# Builds a docker image, publishes it to GitHub's docker repo (ghcr.io),
# and subsequently deploys it as a Container App revision.
#
# The workflow will only run if commit message contains [tag:patch|minor|major]

name: Deploy Update

on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
    # secrets:
    #   BUF_USER:
    #     required: true
    #   BUF_PAT:
    #     required: true
    #   GH_USER:
    #     required: true
    #   GH_PAT:
    #     required: true
    #   GH_ORG:
    #     required: true

env:
  IMAGE_REPO: ghcr.io/${{ github.repository }}

jobs:
  # ----------------------------------------------------
  # Deploy specified build
  # ----------------------------------------------------
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    env:
      ENV: stg
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          # creds: ${{ secrets.AZURE_CREDENTIALS }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to ContainerApp
        uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.event.repository.name }}
          scope: resourcegroup
          # subscriptionId: ${{ env.SUBSCRIPTION }}
          # resourceGroupName: ${{ env.RESOURCE_GROUP }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: app-ticc-${{ env.ENV }}-ae-rg
          template: .github/bicep/main.bicep
          parameters: .github/bicep/params.json appName=${{ github.event.repository.name }} managedEnvName=cae-ticc-${{ env.ENV }} apiManagerName=apim-ticc-${{ env.ENV }} imageName=${{ inputs.image-tag }} mongoUri=${{ secrets.MONGO_URI }} ghcrUser=${{ secrets.GHCR_USER }} ghcrPat=${{ secrets.GHCR_PAT }}
          failOnStdErr: false
