# Deploys the specified docker image as a Container App.

# https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows

name: Deploy Container App

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      func-name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: package
          path: ${{ github.workspace }}/output
          

      - name: "Run Azure Functions Action"
        uses: azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ inputs.func-name }}'
          package: ${{ github.workspace }}/output
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
