# Deploys the specified docker image as a Container App.

# https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows

name: Build and deploy static web app

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      # tag:
      #   type: string
      #   description: |
      #     GitHub tag to use to select image to deploy. Expected in format 'v1.2.3', 
      #     e.g. 'v0.5.0-beta.1'. If nothing is specified, the latest release tag will be used.

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: write
      packages: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate version
        id: version
        uses: paulhatch/semantic-version@v5.0.2

      - name: npm config
        env:
          BUF_NPM_TOKEN: ${{ secrets.BUF_NPM_TOKEN }}
        run: |
          echo "//buf.build/gen/npm/v1/:_authToken=$BUF_NPM_TOKEN" >> .npmrc

      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: /
          output_location: dist
          # app_location: dist
          # skip_app_build: true

      - name: Tag repo
        if: ${{ inputs.environment }} == 'development'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.version.outputs.version_tag }}",
              sha: context.sha
            })